name: CICD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: flip-ip
  MANIFEST_DIR: argocd/apps
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  RUN_NUMBER: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:app-${{ github.run_number }}
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: deploying application with new image tag
        with:
          repository: 'daviinaa/argocd-manifests'
          token: ${{ secrets.GIT_TOKEN }}
          ref: main
      - name: update image
        run: |
          cd ${{ env.MANIFEST_DIR }}
          sed -i "s|${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}.*|${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:app-${{ github.run_number }}|g" flip-values.yaml
          git config user.email theanthonydavina@gmail.com
          git config user.name daviinaa
          git add flip-values.yaml
          git diff --staged  # Debugging: print the changes to be committed
          git commit -m "Done by Github Actions Job changemanifest: ${{ github.run_number }}"
          git push origin main