name: CICD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: flip-ip
  MANIFEST_DIR: argocd/apps

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} .
          echo "::set-output name=IMAGE_TAG::${IMAGE_TAG}"

      - name: Push Docker image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-deploy.outputs.IMAGE_TAG }}

      - name: Deploy application via argcd

      - name: deploy application via argcd
        run: |
          cd ${{ env.MANIFEST_DIR }}
          ls
          cat flip-values.yaml
          sed -i 's|image:\s*repository:.*|image:\n    repository: '${{ env.DOCKERHUB_USERNAME }}'/'${{ env.IMAGE_NAME }}':'${{ needs.build-and-deploy.outputs.IMAGE_TAG }}'|' flip-values.yaml
          cat flip-values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add flip-values.yaml
          git commit -m "Update application with new image tag"
          git push